# Site Settings
title: I Brew Code
tagline: Bugfixing my life
logo: i<span class='alt'>brew</span>code
email: contact@ibrewcode.com
description: Programming and probably more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ibrewcode.com" # the base hostname & protocol for your site
google_analytics: "UA-108800182-1"

# User Settings
username: "Nic Brosz"
user_description: A new software developer jumping into the wild world of code.
disqus_username: i-brew-code

# Social Media
# Remove the item if you don't need it
github_username: nbrosz
# facebook_username: facebook_username
twitter_username: nbrosz
# instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username

# Build settings
# markdown: kramdown
# highlighter: rouge
permalink: /:title/

markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Plugins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate # Provide pagination using the official Jekyll pagination gem
  # - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  # - title: About
  #   url: /about/
  - title: Contact
    url: /contact/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - package.json
  - src
  - node_modules

#exclude: ['package.json', 'src', 'node_modules']

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"